name: Mejora Documentacion
on:
  # Execute when a comment is created in a file of a pull request
  #pull_request_review_comment:
    #types: [ created ]
  workflow_dispatch:
 
jobs:
  Tranlate:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: ${{ github.actor }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Traduciendo markdown
        # uses: trystan2k/md-translator-reviewer@3125179041a779cc7dc7d9fa9428c6b3a89c98cd
        uses: trystan2k/md-translator-reviewer@v1.1.1
        with:
          # GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)
          #token: # optional, default is ${{ github.token }}
          # API Key to use the AI service
          aiApiKey: ${{secrets.AI_API_KEY}}
          # AI Provider
          aiProvider: google
          # optional, default is google
          # AI language model to use.
          #aiModel: # optional, default is gemini-1.5-flash
          # Commit message template when creating new translated file. %file is replaced with the file name and %lang with language
          translateCommitMessageTemplate: add translation of file %README.md for language %english
          # Commit message template when creating a reviewed file. %file is replaced with the file name
          applyReviewCommitMessageTemplate: apply review suggestions for file %README.md
          
