name: Mejora Documentacion
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'
jobs:
  Tranlate:
    runs-on: ubuntu-latest
    env:
       OPENAI_API_KEY: ${{secrets.AI_API_KEY}}
       github-token: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Leer el texto a traducir
        id: read_text
        run: |
          texto=$(cat README.md)
          echo "::set-output name=README::$texto"
      - name: user OpenAI para traducir
        id: translate_text
        uses: actions/github-script@v6
        with:
          script: |
            const text = context.payload.texto_a_traducir;
            const response = await openai.completions.create({
              engine: 'text-davinci-003', # o cualquier otro modelo suitable
              prompt: `Translate the following Spanish text to English:\n\n${text}`,
              max_tokens: 1000, # ajusta según la longitud del texto
              temperature: 0.5,  #Ajusta para controlar la "creatividad" de la traducción
            });        
            const translation = response.data.choices[0].text.trim();
            console.log("Traducción:", translation);      
            return translation;
      - name: Escribir la traducción a un archivo
        run: |
          echo "${{ steps.translate_text.outputs.result }}" > README_en.md
      - name: Commit del archivo traducido (Opcional - Requiere permisos de escritura)
        if: steps.translate_text.outputs.result
        uses: actions/github-script@v6
        with:           
           script: |
             const fs = require('fs');
             const translatedContent = fs.readFileSync('README_en.md', 'utf-8');     
             await github.rest.repos.createOrUpdateFileContents({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: 'README_en.md',
                message: 'Traducción automática del texto',
                content: translatedContent.toString('base64'),
                committer: {
                   name: 'github-actions[bot]',
                   email: 'github-actions[bot]@users.noreply.github.com'
                },
               branch: 'main'
              });
