name: Traductor Gemini

on:
  workflow_dispatch: # Ejecución manual

jobs:
  traducir:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # O la versión de Python que necesites

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai

      - name: Obtener la clave de la API de Gemini
        env:
            GEMINI_API_KEY: ${{ secrets.AI_API_KEY }}
        run: |
           echo "GEMINI_API_KEY=$GEMINI_API_KEY" >> $GITHUB_ENV #Forma recomendada de setear variables de entorno


      - name: Ejecutar el script traductor.py (Ejemplo con archivos de prueba)
        run: |
          python traductor.py README.md README_en.md

      - name: Commit de los cambios (si se generan nuevos archivos)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Traducción automática con Gemini"
          file_pattern: *.md # Ajusta según los archivos que genere tu script
