name: Mejora Documentacion
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'
jobs:
  Translate:
    runs-on: ubuntu-latest
    env:
       OPENAI_API_KEY: ${{secrets.AI_API_KEY}}
       GITHUB_TOKEN: ${{secrets.TRADUCTOR_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Leer el texto a traducir
        id: read_text
        run: |
          texto=$(cat README.md)
          echo "::set-output name=README::$texto"
      - name: Install OpenAI Python Library
        run: pip install openai
      - name: user OpenAI para traducir
        id: translate_text
        uses: actions/github-script@v6
      
        with:
          script: |
            const fs = require('fs');
            const text = fs.readFileSync('./README.md', 'utf-8'); // Lee el archivo directamente
            const { Configuration, OpenAIApi } = require("openai");
            const configuration = new Configuration({
              apiKey: process.env.OPENAI_API_KEY,
            });
            const openai = new OpenAIApi(configuration);          
            const response = await openai.completions.create({
              model: 'text-davinci-003',
              prompt: `Translate the following Spanish text to English:\n\n${text}`,
              max_tokens: 2048, # Aumentado para textos más largos
              temperature: 0.5,
            });
            const translation = response.data.choices[0].text.trim();
            console.log("Traducción:", translation);      
            return translation;
      - name: Escribir la traducción a un archivo
        run: |
          echo "${{ steps.translate_text.outputs.result }}" > README_en.md
      - name: Commit del archivo traducido (Opcional - Requiere permisos de escritura)
        if: steps.translate_text.outputs.result
        uses: actions/github-script@v6
        with:           
           script: |
             const fs = require('fs');
             const translatedContent = fs.readFileSync('README_en.md', 'utf-8');     
             await github.rest.repos.createOrUpdateFileContents({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: 'README_en.md',
                message: 'Traducción automática del texto',
                content: translatedContent.toString('base64'),
                committer: {
                   name: 'github-actions[bot]',
                   email: 'github-actions[bot]@users.noreply.github.com'
                },
               branch: 'main'
              });
